### ISSUE TITLE
How to connect eks endpoint from lambda in vpc

### ISSUE THREAD

**Issue by tonygitworld** [aws-samples/amazon-k8s-node-drainer#19] opened 2019-09-26 11:48 UTC
Hi there,

    Why it showed the warning messages as below when I config the "VpcConfig" property of "AWS::Serverless::Function" in the template.yaml.

        ---
        2019-09-25 08:21:10,539 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f92e39c43d0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/nodes?includeUninitialized=True&pretty=True
        
        08:21:10
        [WARNING]   2019-09-25T08:21:10.539Z    e0b2d964-f400-47cd-b29f-253e7fe463e5    Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f92e39c43d0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/nodes?includeUninitialized=True&pretty=True
        [WARNING]   2019-09-25T08:21:10.539Z    e0b2d964-f400-47cd-b29f-253e7fe463e5    Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f92e39c43d0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/nodes?includeUninitialized=True&pretty=True
        ---
     
    However, I can make sure this private subnet and the security group allow the traffic to the EKS API server endpoint since I launched an EC2 instance in the same subnet and the same security group, and I can dig/curl the EKS API server endpoint.

    I found there's a description in the README.md  on github:
     
        NB: The lambda function created assumes that the Amazon EKS cluster's Kubernetes API server endpoint has public access enabled, if your endpoint only has private access enabled then you must modify the template.yml file to ensure the lambda function is running in the correct VPC and subnet.
       
    Therefore, I assumed it runs the function within the VPC private subnet should work. Could you please point out how to correctly conifgure the VPC for the function? Or, should I do any thing else other than just configure "VpcConfig" property to make it work?
     
    Thanks for your help in advance.

**Comment by svozza** [comment] 2019-09-27 14:28
Hi Tony, I'll try to reproduce this and investigate.

**Comment by svozza** [comment] 2019-10-10 09:30
Looks like this was a misconfiguration in the lambda security group so I'm closing this.

**Closed** 2019-11-01 14:27 UTC

**Comment by anandgia** [comment] 2020-05-09 05:35
@svozza could you explain what the security group issue could be. I have a private EKS and run into the same issue. The lambda is in private subnet inside a VPC which has a NAT instance in public subnet. The lambda's security group allows all 443 inbound traffic and all outgoing traffic.

`2020/05/09/[$LATEST]bc39b8f0776748c8b93313f8928118dc 2020-05-09T05:26:39.214000 START RequestId: fa0dfda9-5437-492f-8816-adab58f8bbbd Version: $LATEST
2020/05/09/[$LATEST]bc39b8f0776748c8b93313f8928118dc 2020-05-09T05:26:39.219000 [INFO]	2020-05-09T05:26:39.218Z	fa0dfda9-5437-492f-8816-adab58f8bbbd	Instance ID: i-04c1f190ff38fc846
2020/05/09/[$LATEST]bc39b8f0776748c8b93313f8928118dc 2020-05-09T05:26:39.395000 [INFO]	2020-05-09T05:26:39.395Z	fa0dfda9-5437-492f-8816-adab58f8bbbd	Node name: ip-10-150-162-192.us-west-2.compute.internal
2020/05/09/[$LATEST]bc39b8f0776748c8b93313f8928118dc 2020-05-09T05:31:01.490000 2020-05-09 05:31:01,489 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdacae31110>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/nodes?includeUninitialized=True&pretty=True
2020/05/09/[$LATEST]bc39b8f0776748c8b93313f8928118dc 2020-05-09T05:31:01.490000 [WARNING]	2020-05-09T05:31:01.489Z	fa0dfda9-5437-492f-8816-adab58f8bbbd	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdacae31110>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/nodes?includeUninitialized=True&pretty=True`

**Comment by anandgia** [comment] 2020-05-09 06:17
@svozza figured out the issue, for any future reference one potential issue is the security group associated with the EKS cluster itself. In the additional security group ensure that 443 access is opened up for the lambda subnet.
