### ISSUE TITLE
Module import error - yaml

### ISSUE THREAD

**Issue by ahillman3** [aws-samples/amazon-k8s-node-drainer#22] opened 2019-11-26 20:05 UTC
I'm trying to install this with a new installation of EKS using eksctl, and have not been able to successfully execute the lambda.

I get this error in the logs:
Unable to import module 'handler': No module named 'yaml'

I tried using Python 3.7 and 3.6 with no success.
Any suggestions?

**Comment by HieronymusLex** [comment] 2019-12-05 09:58
hi @ahillman3 - the error suggests that the `yaml` dependency is missing from the Lambda package. Did you build the deployment artefact first using `sam build --use-container --skip-pull-image`? 

You can use the `build_deploy.sh` wrapper script to deploy the solution which runs the relevant SAM (build/package/deploy) commands for you i.e.
```
./build_deploy.sh 
    ${BUCKET_NAME} \
    ${YOUR_AUTOSCALING_GROUP_NAME} \
    ${YOUR_CLUSTER_NAME} \
    ${YOUR_AWS_PROFILE}
```

**Comment by HieronymusLex** [comment] 2019-12-09 09:35
Closing this for now as running SAM build will ensure dependencies are packaged correctly. If the issue isn't resolved please feel free to reopen!

**Closed by HieronymusLex** 2019-12-09 09:35 UTC
